-- languages: the two languages this plugin adds to the code editor. Each one is data.
--
-- `comment` names the mark that starts a comment, so `#` starts one and `/*` opens nothing. A
-- Proteus from before `comment` colors these files with its rules for C, and there
-- `directive` still gives `#` lines a color of their own.

---@class LangGdscript.LanguagesModule
local M = {}

---GDScript, the language of Godot 4's scripts.
---@type Proteus.LanguageSpec
M.gdscript = {
  name = 'gdscript',
  extensions = { 'gd' },
  keywords = {
    'and',
    'as',
    'assert',
    'await',
    'break',
    'breakpoint',
    'class',
    'class_name',
    'const',
    'continue',
    'elif',
    'else',
    'enum',
    'extends',
    'for',
    'func',
    'if',
    'in',
    'is',
    'match',
    'not',
    'or',
    'pass',
    'preload',
    'return',
    'signal',
    'static',
    'super',
    'var',
    'when',
    'while',
  },
  -- The line after one of these indents, the way Godot's own editor does it after a `:`.
  block_keywords = 'func if elif else for while match class',
  types = {
    'void',
    'bool',
    'int',
    'float',
    'String',
    'StringName',
    'NodePath',
    'Variant',
    'Object',
    'Callable',
    'Signal',
    'Array',
    'Dictionary',
    'RID',
    'Color',
    'Vector2',
    'Vector2i',
    'Vector3',
    'Vector3i',
    'Vector4',
    'Vector4i',
    'Rect2',
    'Rect2i',
    'Transform2D',
    'Transform3D',
    'Basis',
    'Quaternion',
    'Plane',
    'AABB',
    'Projection',
    'PackedByteArray',
    'PackedInt32Array',
    'PackedInt64Array',
    'PackedFloat32Array',
    'PackedFloat64Array',
    'PackedStringArray',
    'PackedVector2Array',
    'PackedVector3Array',
    'PackedVector4Array',
    'PackedColorArray',
    'Node',
    'Node2D',
    'Node3D',
    'Control',
    'CanvasItem',
    'CanvasLayer',
    'Resource',
    'RefCounted',
    'PackedScene',
    'SceneTree',
    'Viewport',
    'Window',
    'Sprite2D',
    'Sprite3D',
    'AnimatedSprite2D',
    'AnimationPlayer',
    'CharacterBody2D',
    'CharacterBody3D',
    'RigidBody2D',
    'RigidBody3D',
    'StaticBody2D',
    'StaticBody3D',
    'Area2D',
    'Area3D',
    'CollisionShape2D',
    'CollisionShape3D',
    'Camera2D',
    'Camera3D',
    'MeshInstance3D',
    'TileMapLayer',
    'Timer',
    'Tween',
    'Label',
    'Button',
    'Panel',
    'TextureRect',
    'Container',
    'HBoxContainer',
    'VBoxContainer',
    'MarginContainer',
    'Texture2D',
    'AudioStreamPlayer',
    'AudioStreamPlayer2D',
    'InputEvent',
    'InputEventKey',
    'InputEventMouseButton',
    'Input',
    'Engine',
    'OS',
    'Time',
    'JSON',
    'FileAccess',
    'DirAccess',
    'ResourceLoader',
    'ProjectSettings',
  },
  builtins = {
    'abs',
    'absf',
    'absi',
    'acos',
    'asin',
    'atan',
    'atan2',
    'ceil',
    'char',
    'clamp',
    'clampf',
    'clampi',
    'cos',
    'deg_to_rad',
    'exp',
    'floor',
    'fmod',
    'get_stack',
    'instance_from_id',
    'inverse_lerp',
    'is_equal_approx',
    'is_instance_of',
    'is_instance_valid',
    'is_zero_approx',
    'len',
    'lerp',
    'lerpf',
    'load',
    'log',
    'max',
    'maxf',
    'maxi',
    'min',
    'minf',
    'mini',
    'move_toward',
    'pow',
    'print',
    'print_debug',
    'print_stack',
    'printerr',
    'prints',
    'push_error',
    'push_warning',
    'rad_to_deg',
    'randf',
    'randf_range',
    'randi',
    'randi_range',
    'randomize',
    'range',
    'remap',
    'round',
    'sign',
    'sin',
    'smoothstep',
    'snapped',
    'sqrt',
    'str',
    'str_to_var',
    'tan',
    'type_exists',
    'typeof',
    'var_to_str',
    'weakref',
    'wrap',
    'wrapf',
    'wrapi',
  },
  atoms = 'true false null self PI TAU INF NAN',
  -- Annotations such as `@export` and `@onready`.
  attribute = '@',
  comment = '#',
  directive = '#',
}

---Godot's scenes, resources and settings files. They read like an ini file: sections in
---brackets, and `key = value` lines.
---@type Proteus.LanguageSpec
M.resource = {
  name = 'godotresource',
  extensions = { 'tscn', 'tres', 'godot', 'import' },
  keywords = {
    'gd_scene',
    'gd_resource',
    'ext_resource',
    'sub_resource',
    'resource',
    'node',
    'connection',
    'editable',
    'remap',
    'deps',
    'params',
  },
  types = {
    'ExtResource',
    'SubResource',
    'NodePath',
    'StringName',
    'Object',
    'Array',
    'Dictionary',
    'Color',
    'Vector2',
    'Vector2i',
    'Vector3',
    'Vector3i',
    'Vector4',
    'Rect2',
    'Rect2i',
    'Transform2D',
    'Transform3D',
    'Basis',
    'Quaternion',
    'AABB',
    'PackedByteArray',
    'PackedInt32Array',
    'PackedFloat32Array',
    'PackedStringArray',
    'PackedVector2Array',
    'PackedVector3Array',
    'PackedColorArray',
  },
  atoms = 'true false null',
  comment = ';',
}

return M
