-- language: Luau as a language the code editor colors, for `.luau` files. It is data: Luau's
-- words, and `--` as the mark that starts a comment. A Proteus from before `comment` colors
-- the file with its rules for C, where `--` is no comment.
--
-- The editor colors one line at a time, so a `--[[ block ]]` comment colors only its first
-- line.

---@type Proteus.LanguageSpec
return {
  name = 'luau',
  extensions = { 'luau' },
  keywords = {
    'local',
    'function',
    'end',
    'if',
    'then',
    'elseif',
    'else',
    'for',
    'in',
    'do',
    'while',
    'repeat',
    'until',
    'return',
    'break',
    'continue',
    'and',
    'or',
    'not',
    'type',
    'export',
    'typeof',
  },
  -- The line after one of these indents.
  block_keywords = 'function if elseif else for while repeat do',
  -- `string` and `buffer` name types too. They are in builtins, which color the same.
  types = 'number boolean any unknown never thread userdata vector',
  builtins = {
    -- Luau's own globals and libraries.
    'assert',
    'error',
    'gcinfo',
    'getmetatable',
    'ipairs',
    'newproxy',
    'next',
    'pairs',
    'pcall',
    'print',
    'rawequal',
    'rawget',
    'rawlen',
    'rawset',
    'require',
    'select',
    'setmetatable',
    'tonumber',
    'tostring',
    'unpack',
    'xpcall',
    'bit32',
    'buffer',
    'coroutine',
    'debug',
    'math',
    'os',
    'string',
    'table',
    'utf8',
    -- Roblox's globals.
    'game',
    'workspace',
    'script',
    'plugin',
    'shared',
    'task',
    'warn',
    'tick',
    'time',
    'wait',
    'delay',
    'spawn',
    'elapsedTime',
    'settings',
    'UserSettings',
    'Enum',
    'Instance',
    'Axes',
    'BrickColor',
    'CFrame',
    'Color3',
    'ColorSequence',
    'ColorSequenceKeypoint',
    'DateTime',
    'Faces',
    'Font',
    'NumberRange',
    'NumberSequence',
    'NumberSequenceKeypoint',
    'OverlapParams',
    'PathWaypoint',
    'PhysicalProperties',
    'Random',
    'Ray',
    'RaycastParams',
    'Rect',
    'Region3',
    'Region3int16',
    'SharedTable',
    'TweenInfo',
    'UDim',
    'UDim2',
    'Vector2',
    'Vector2int16',
    'Vector3',
    'Vector3int16',
  },
  atoms = 'true false nil',
  comment = '--',
}
